### ISSUE TITLE
Tutorial: Module parse failed

### ISSUE THREAD

**Issue by caisah** [angular-class/ES6-build-tools#2]
Hi, 
I have followed the tutorial, but when i try to build with 
`webpack ./client/app.js ./client/bundle.js --module-bind 'js=babel'`
it fails with:

`client/app.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import greeting from './content';
| // We can use any ES6 syntax supported by Babel here now!
| alert(`${ greeting } and with ES6!!`);`

Do you know what the problem could be?

**Comment by arturoromeroslc** [comment]
You could try removing the pipes before and after the import line `import greeting from './content';`, as that is not correct JS syntax.

**Comment by blakeembrey** [comment]
@caisah Have you tried loading a preset for Babel? 

@arturoromerotcs I believe the pipes are from the CLI output of Babel, not in the actual code (you'll notice it's the start of every line.

**Comment by juaniiie** [comment]
@caisah, I encountered the same issue and fixed it by loading a preset for Babel. Thank you for the suggestion @blakeembrey  !

These are the steps I took to fix the issue:
1. Installed babel preset: `npm install babel-preset-es2015 --save-dev`
2. Added a `.babelrc` file to the root directory with the following code: `{ "presets": ["es2015"] }`

**Comment by caisah** [comment]
@juaniiie @blakeembrey Thanks!
